apiVersion: v1 
kind: Pod
metadata:
  name: fiap-game
  labels:
    app: fiap-game
spec:
  containers:
  - name: fiap-game
    image: devluis27/fiap-game
    volumeMounts:
     - name: shared
       mountPath: /usr/share/nginx/html
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: fiap-pvc
