apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DATABASE_URL: jdbc:postgresql://postgres-service:5432/pedidos
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DB_PASSWORD: dXNlclBhc3M=  # Valor codificado em Base64
  MERCADO_PAGO_TOKEN: abc123xyz456=
