apiVersion: v1
kind: Service
metadata:
  name: svc-fiap-adm
spec:
  type: ClusterIP
  selector:
    app: fiap-svc-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


#--
#apiVersion: v1
#kind: Service
#metadata:
#  name: svc-fiap-adm
#spec:
#  type: NodePort
#  selector:
#    app: fiap-svc-1
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 31100:3000

