apiVersion: v1
kind: Pod 
metadata:
  name: pod-empty-vol
  labels:
    name: pod-empty-vol
spec:
  containers:
  - name: container-empty-vol
    image: devluis27/fiap-site-1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: cdn
      mountPath: /usr/share/nginx/html
  volumes:
  - name: cdn
    emptyDir: {}